
import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
/* Import STRIPE_PAYMENT_LINK from constants */
import { INITIAL_PRODUCTS, ADJECTIVES, NOUNS, UNSPLASH_IDS, FUTURE_YEAR, FEATURED_PRODUCT, STRIPE_PAYMENT_LINK } from '../constants';
import ProductCard from '../components/ProductCard';
import { Filter, Search, ChevronLeft, ChevronRight, Zap, Clock, Cpu, Sliders, CheckCircle2, Download, Terminal } from 'lucide-react';
import { Product, Category } from '../types';

const Marketplace: React.FC = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [products, setProducts] = useState<Product[]>(INITIAL_PRODUCTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const [tuningAsset, setTuningAsset] = useState<Product | null>(null);
  
  const totalPages = 54883237565; 
  const categories = ['All', ...Object.values(Category)];

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    if (currentPage === 1 && !searchQuery) {
      setProducts(INITIAL_PRODUCTS);
      return;
    }
    setIsGenerating(true);
    const timer = setTimeout(() => {
      const newProducts = Array.from({ length: 6 }).map((_, index) => {
        const seed = (currentPage * 13) + index * 7;
        const adj = ADJECTIVES[seed % ADJECTIVES.length];
        const noun = NOUNS[(seed * 3) % NOUNS.length]; 
        const catList = Object.values(Category);
        const cat = catList[seed % catList.length];
        const imgIndex = (currentPage * 17 + index * 23) % UNSPLASH_IDS.length;
        const imgId = UNSPLASH_IDS[imgIndex];
        return {
          id: `agi-gen-${currentPage}-${index}`,
          name: `${adj} ${noun} ${FUTURE_YEAR}`,
          description: `Elite ${cat.toLowerCase()} generated by Deep Learning AGI Swarms. Optimized for ${FUTURE_YEAR} market leverage.`,
          price: 19.00 + (seed % 150) + 0.99,
          category: cat,
          image: `https://images.unsplash.com/photo-${imgId}?auto=format&fit=crop&q=80&w=600`,
          rating: 4.8,
          salesCount: 400 + (seed % 1000),
          roi: `${(seed % 20) + 5}x Potential`,
          demandScore: 70 + (seed % 29)
        };
      });
      setProducts(newProducts);
      setIsGenerating(false);
    }, 600);
    return () => clearTimeout(timer);
  }, [currentPage]);

  const displayedProducts = products.filter(p => {
    const matchesCategory = activeCategory === 'All' || p.category === activeCategory;
    const matchesSearch = p.name.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="pt-32 md:pt-28 min-h-screen bg-white">
      <div className="max-w-7xl mx-auto px-4 pb-20">
        
        {/* Marketplace Header */}
        <div className="mb-12 bg-black text-white p-8 rounded-sm border border-gray-800 shadow-2xl relative overflow-hidden">
           <div className="absolute top-0 right-0 p-12 opacity-10 pointer-events-none">
              <Terminal className="w-64 h-64" />
           </div>
           <div className="relative z-10 flex flex-col md:flex-row justify-between items-center gap-8">
              <div>
                <p className="text-blue-400 font-mono text-[10px] uppercase tracking-[0.4em] mb-3">Live Asset Synthesis</p>
                <h1 className="text-4xl font-black uppercase tracking-tighter">AGI Marketplace</h1>
                <p className="text-zinc-500 text-sm mt-2 max-w-lg">Browsing 54.8 Billion systemic variants. Select a node to initiate structural tuning.</p>
              </div>
              <div className="flex space-x-12">
                 <div className="text-center">
                    <p className="text-[9px] font-black uppercase text-zinc-500 mb-1">Batch Status</p>
                    <p className="text-green-500 font-bold tracking-widest text-sm">OPTIMIZED</p>
                 </div>
                 <div className="text-center">
                    <p className="text-[9px] font-black uppercase text-zinc-500 mb-1">Compute Cost</p>
                    <p className="text-white font-bold tracking-widest text-sm">0.002 SOL</p>
                 </div>
              </div>
           </div>
        </div>

        {/* Global Search & Tuning Modal */}
        <div className="grid grid-cols-12 gap-8">
           <div className="col-span-12 lg:col-span-3 space-y-8">
              <div className="bg-zinc-50 border border-zinc-200 p-6 rounded-sm">
                 <p className="text-[10px] font-black uppercase tracking-widest mb-6">Filter Matrix</p>
                 <div className="relative mb-6">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-400" />
                    <input type="text" placeholder="Search variants..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className="w-full pl-10 pr-4 py-3 bg-white border border-zinc-200 text-xs font-bold uppercase rounded-sm outline-none focus:border-black transition-all" />
                 </div>
                 <div className="space-y-2">
                    {categories.map(cat => (
                      <button key={cat} onClick={() => setActiveCategory(cat)} className={`w-full text-left py-2 px-3 text-[10px] font-bold uppercase tracking-widest transition-all ${activeCategory === cat ? 'bg-black text-white' : 'text-zinc-500 hover:bg-zinc-100'}`}>
                        {cat}
                      </button>
                    ))}
                 </div>
              </div>

              {/* Node Stats Widget */}
              <div className="bg-black text-white p-6 rounded-sm shadow-xl relative overflow-hidden">
                 <div className="absolute -right-4 -bottom-4 w-24 h-24 bg-blue-600/10 rounded-full blur-2xl"></div>
                 <p className="text-[9px] font-black uppercase tracking-widest text-zinc-500 mb-4">Network Status</p>
                 <div className="flex items-center space-x-2 text-green-400 mb-2">
                    <div className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse"></div>
                    <span className="text-[10px] font-bold uppercase tracking-widest">Nodes Operational</span>
                 </div>
                 <p className="text-2xl font-black tracking-tighter">4,092,822</p>
              </div>
           </div>

           <div className="col-span-12 lg:col-span-9">
              {isGenerating ? (
                <div className="py-40 flex flex-col items-center justify-center space-y-6">
                   <div className="w-16 h-16 border-4 border-zinc-100 border-t-black rounded-full animate-spin"></div>
                   <p className="text-[10px] font-black uppercase tracking-[0.4em] text-zinc-400 animate-pulse">Synthesizing Asset Batch...</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
                   {displayedProducts.map(product => (
                     <div key={product.id} className="relative group">
                        <ProductCard product={product} />
                        <button 
                          onClick={() => setTuningAsset(product)}
                          className="absolute bottom-24 right-6 bg-white/90 backdrop-blur p-3 rounded-sm shadow-xl opacity-0 group-hover:opacity-100 transition-all border border-zinc-200 hover:border-black"
                          title="Structural Tune"
                        >
                           <Sliders className="w-4 h-4" />
                        </button>
                     </div>
                   ))}
                </div>
              )}
              
              {/* Pagination */}
              <div className="mt-16 pt-8 border-t border-zinc-100 flex justify-between items-center">
                 <button onClick={() => setCurrentPage(p => Math.max(1, p-1))} className="text-[10px] font-black uppercase tracking-widest flex items-center hover:text-zinc-500 transition-colors">
                    <ChevronLeft className="w-4 h-4 mr-2" /> Prev Batch
                 </button>
                 <span className="text-[10px] font-mono text-zinc-400">PAGE {currentPage.toLocaleString()} / {totalPages.toLocaleString()}</span>
                 <button onClick={() => setCurrentPage(p => p+1)} className="text-[10px] font-black uppercase tracking-widest flex items-center hover:text-zinc-500 transition-colors">
                    Next Batch <ChevronRight className="w-4 h-4 ml-2" />
                 </button>
              </div>
           </div>
        </div>

        {/* Tuning Modal (The "Asset Customizer" Feature) */}
        {tuningAsset && (
          <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
             <div className="bg-white w-full max-w-3xl rounded-sm overflow-hidden shadow-[0_0_100px_rgba(0,0,0,0.5)] animate-in zoom-in-95 duration-300">
                <div className="flex flex-col md:flex-row h-full">
                   <div className="md:w-1/2 bg-zinc-50 border-r border-zinc-100 p-8">
                      <div className="relative aspect-square mb-6 overflow-hidden border border-zinc-200">
                        <img src={tuningAsset.image} className="w-full h-full object-cover grayscale" />
                      </div>
                      <h3 className="text-xl font-bold uppercase tracking-tighter mb-2">{tuningAsset.name}</h3>
                      <p className="text-[10px] text-zinc-500 font-medium leading-relaxed uppercase tracking-widest">{tuningAsset.description}</p>
                   </div>
                   <div className="md:w-1/2 p-8 flex flex-col justify-between">
                      <div>
                         <div className="flex justify-between items-center mb-8">
                            <span className="text-[9px] font-black uppercase tracking-widest text-zinc-400">Asset Tuning v4</span>
                            <button onClick={() => setTuningAsset(null)} className="text-zinc-400 hover:text-black">
                               <Zap className="w-5 h-5" />
                            </button>
                         </div>
                         <div className="space-y-8">
                            <div className="space-y-4">
                               <label className="text-[9px] font-black uppercase tracking-widest">Recursive Depth</label>
                               <input type="range" className="w-full h-1 bg-zinc-100 accent-black appearance-none rounded-full" />
                            </div>
                            <div className="space-y-4">
                               <label className="text-[9px] font-black uppercase tracking-widest">Market Alignment</label>
                               <div className="grid grid-cols-2 gap-2">
                                  <button className="bg-black text-white py-2 text-[8px] font-black uppercase tracking-widest">Aggressive</button>
                                  <button className="bg-zinc-50 border border-zinc-200 py-2 text-[8px] font-black uppercase tracking-widest">Sovereign</button>
                               </div>
                            </div>
                            <div className="space-y-4">
                               <label className="text-[9px] font-black uppercase tracking-widest">Output Modality</label>
                               <select className="w-full border border-zinc-200 p-3 text-[10px] font-bold uppercase tracking-widest rounded-sm">
                                  <option>PDF-RAW</option>
                                  <option>JSON-SCHEMA</option>
                                  <option>MARKDOWN-BLUEPRINT</option>
                               </select>
                            </div>
                         </div>
                      </div>
                      <div className="pt-8 mt-8 border-t border-zinc-100 flex items-center justify-between">
                         <span className="text-2xl font-black tabular-nums">${tuningAsset.price.toFixed(2)}</span>
                         <a href={STRIPE_PAYMENT_LINK} className="bg-black text-white px-8 py-4 text-[10px] font-black uppercase tracking-widest rounded-sm hover:bg-zinc-800 transition-all shadow-xl">
                            Lock & Acquire
                         </a>
                      </div>
                   </div>
                </div>
             </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Marketplace;
