import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { INITIAL_PRODUCTS, ADJECTIVES, NOUNS, UNSPLASH_IDS, FUTURE_YEAR } from '../constants';
import ProductCard from '../components/ProductCard';
import { Filter, Search, ChevronLeft, ChevronRight, Zap, Clock, Cpu } from 'lucide-react';
import { Product, Category } from '../types';

const Marketplace: React.FC = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [products, setProducts] = useState<Product[]>(INITIAL_PRODUCTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const location = useLocation();
  
  const totalPages = 54883237565; 

  const categories = ['All', ...Object.values(Category)];

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const searchParam = params.get('search');
    if (searchParam) {
      setSearchQuery(searchParam);
      if (currentPage === 1) {
         setCurrentPage(2);
      }
    }
  }, [location.search]);

  const today = new Date();
  const daysUntilSync = 7 - (today.getDay() % 7);
  const hoursUntilSync = 23 - today.getHours();

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });

    if (currentPage === 1 && !searchQuery) {
      setProducts(INITIAL_PRODUCTS);
      return;
    }

    setIsGenerating(true);

    const timer = setTimeout(() => {
      const newProducts = Array.from({ length: 6 }).map((_, index) => {
        const seed = (currentPage * 13) + index * 7;
        const adj = ADJECTIVES[seed % ADJECTIVES.length];
        const noun = NOUNS[(seed * 3) % NOUNS.length]; 
        const catList = Object.values(Category);
        const cat = catList[seed % catList.length];
        
        const imgIndex = (currentPage * 17 + index * 23) % UNSPLASH_IDS.length;
        const imgId = UNSPLASH_IDS[imgIndex];

        return {
          id: `agi-gen-${currentPage}-${index}`,
          name: `${adj} ${noun} ${FUTURE_YEAR + (seed % 3)}`,
          description: `An elite ${cat.toLowerCase()} generated by Deep Learning AGI Swarms for the ${FUTURE_YEAR} market. Engineered for maximum output.`,
          price: 19.00 + (seed % 150) + 0.99,
          category: cat,
          image: `https://images.unsplash.com/photo-${imgId}?auto=format&fit=crop&q=80&w=600`,
          rating: Number((4.5 + ((seed % 5) / 10)).toFixed(1)),
          salesCount: 10 + ((seed * 117) % 800)
        };
      });

      setProducts(newProducts);
      setIsGenerating(false);
    }, 600);

    return () => clearTimeout(timer);
  }, [currentPage]);

  const handleNext = () => setCurrentPage((p) => p + 1);
  const handlePrev = () => setCurrentPage((p) => (p > 1 ? p - 1 : 1));

  const displayedProducts = products.filter(p => {
    const matchesCategory = activeCategory === 'All' || p.category === activeCategory;
    const matchesSearch = p.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          p.description.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="pt-28 md:pt-24 min-h-screen bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-20">
        
        <div className="mb-12 bg-black text-white p-4 md:p-6 flex flex-col md:flex-row justify-between items-center gap-4 rounded-sm border border-gray-800 shadow-2xl">
           <div className="flex items-center space-x-4">
              <div className="relative flex h-4 w-4">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-4 w-4 bg-green-500"></span>
              </div>
              <div>
                <p className="font-bold text-sm uppercase tracking-widest flex items-center"><Cpu className="w-4 h-4 mr-2"/> AGI Autonomous Generation Active</p>
                <p className="text-gray-400 text-xs mt-1">{`Machine Learning algorithms are continuously writing and deploying products for the ${FUTURE_YEAR} market.`}</p>
              </div>
           </div>
           <div className="flex items-center space-x-8 text-sm font-mono text-center md:text-right">
              <div>
                 <div className="text-gray-400">DAILY UPLOAD QUOTA</div>
                 <div className="font-bold text-green-400">100 / 100 Products Added</div>
              </div>
              <div className="hidden md:block w-px h-8 bg-gray-800"></div>
              <div>
                 <div className="text-gray-400">NEXT GLOBAL SYNC</div>
                 <div className="font-bold flex items-center justify-center md:justify-end">
                    <Clock className="w-3 h-3 mr-1" /> {daysUntilSync} Days, {hoursUntilSync} Hours
                 </div>
              </div>
           </div>
        </div>

        <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-12">
          <div>
            <h1 className="text-4xl font-bold tracking-tighter uppercase mb-2">AGI Marketplace</h1>
            <p className="text-gray-500 text-sm font-mono flex items-center">
              Browsing auto-generated catalog <span className="text-black font-bold mx-2">{currentPage.toLocaleString()}</span> / {totalPages.toLocaleString()}
            </p>
          </div>

          <div className="w-full md:w-auto flex flex-col md:flex-row gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search deep learning assets..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full md:w-64 pl-10 pr-4 py-2 border border-gray-200 focus:border-black outline-none text-sm font-mono bg-gray-50 transition-colors focus:bg-white"
              />
            </div>
          </div>
        </div>

        <div className="flex flex-col lg:flex-row gap-8">
          <div className="w-full lg:w-64 flex-shrink-0">
            <div className="sticky top-24">
              <div className="flex items-center space-x-2 mb-6 text-xs font-bold uppercase tracking-widest">
                <span>Filters</span>
              </div>
              <div className="space-y-6">
                <div>
                  <h4 className="text-xs font-bold uppercase text-gray-400 mb-3">Categories</h4>
                  <div className="space-y-2">
                    {categories.map((cat) => (
                      <button
                        key={cat}
                        onClick={() => setActiveCategory(cat)}
                        className={`block text-sm w-full text-left py-1 hover:pl-1 transition-all ${
                          activeCategory === cat ? 'font-bold text-black border-l-2 border-black pl-2' : 'text-gray-500'
                        }`}
                      >
                        {cat}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="pt-8 border-t border-gray-100">
                  <div className="bg-gradient-to-br from-gray-900 to-black text-white p-4 border border-gray-800 relative overflow-hidden">
                    <Zap className="absolute -right-4 -bottom-4 w-24 h-24 text-gray-800 opacity-50" />
                    <p className="text-[10px] font-mono mb-2 text-green-400">AGI NEURAL VAULT</p>
                    <p className="text-sm font-bold mb-4 relative z-10">Sync your brain for 1-click downloads.</p>
                    <button className="w-full bg-white text-black py-2 text-xs font-bold relative z-10 hover:bg-gray-200 transition-colors">INITIATE SYNC</button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex-grow">
            {isGenerating ? (
               <div className="py-32 flex flex-col items-center justify-center space-y-4">
                  <div className="w-12 h-12 border-4 border-gray-200 border-t-black rounded-full animate-spin"></div>
                  <p className="font-mono text-sm text-gray-500 uppercase tracking-widest animate-pulse">AGI Swarm synthesizing new products...</p>
               </div>
            ) : displayedProducts.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
                {displayedProducts.map((product) => (
                  <ProductCard key={product.id} product={product} />
                ))}
              </div>
            ) : (
              <div className="text-center py-20 border border-gray-100 bg-gray-50">
                 <h3 className="text-lg font-bold mb-2">No active variants found</h3>
                 <p className="text-gray-500 text-sm">Adjust your filters or search query to see more quantum assets.</p>
              </div>
            )}

            <div className="mt-20 flex flex-col items-center border-t border-gray-100 pt-12">
              <div className="flex flex-col sm:flex-row items-center space-y-4 sm:space-y-0 sm:space-x-8">
                <button
                  onClick={handlePrev}
                  disabled={currentPage === 1 || isGenerating}
                  className="flex items-center space-x-2 text-sm font-bold disabled:text-gray-200 hover:text-gray-500"
                >
                  <span>PREV BATCH</span>
                </button>
                <div className="flex items-center space-x-2 font-mono text-sm bg-gray-50 px-4 py-2 border border-gray-200 rounded">
                   <span className="font-bold text-black">Page {currentPage.toLocaleString()}</span>
                   <span className="text-gray-400">of</span>
                   <span className="font-bold text-gray-600">{totalPages.toLocaleString()}</span>
                </div>
                <button
                  onClick={handleNext}
                  disabled={isGenerating}
                  className="flex items-center space-x-2 px-6 py-3 bg-black text-white text-sm font-bold hover:bg-gray-800 transition-colors group shadow-lg"
                >
                  <span>NEXT PAGE</span>
                </button>
              </div>
              <p className="mt-8 text-xs text-gray-400 uppercase tracking-widest font-bold flex items-center">
                <Zap className="w-3 h-3 mr-1" />
                Authored by AGI Neural Network #8892
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Marketplace;